version: '3.7'

networks:
    homebiz-net:
        driver: bridge

services:

    #######################################
    # Backend Services
    #######################################

    user:
        image: asia.gcr.io/wad2-286702/homebiz-user
        container_name: user
        restart: always
        ports: 
        - 7001:7001
        networks:
        - homebiz-net
        env_file:
        - ./env/.env

    shop:
        image: asia.gcr.io/wad2-286702/homebiz-shop
        container_name: shop
        restart: always
        ports: 
        - 7002:7002
        networks:
        - homebiz-net
        env_file:
        - ./env/.env

    payment:
        image: asia.gcr.io/wad2-286702/homebiz-payment
        container_name: payment
        restart: always
        ports: 
        - 7006:7006
        networks:
        - homebiz-net
        env_file:
        - ./env/.env

    search:
        image: asia.gcr.io/wad2-286702/homebiz-search
        container_name: search
        restart: always
        ports: 
        - 7009:7009
        networks:
        - homebiz-net
        env_file:
        - ./env/.env

    order:
        image: asia.gcr.io/wad2-286702/homebiz-order
        container_name: order
        restart: always
        ports: 
        - 7003:7003
        networks:
        - homebiz-net
        env_file:
        - ./env/.env

    product:
        image: asia.gcr.io/wad2-286702/homebiz-product
        container_name: product
        restart: always
        ports: 
        - 7004:7004
        networks:
        - homebiz-net
        env_file:
        - ./env/.env

    review:
        image: asia.gcr.io/wad2-286702/homebiz-review
        container_name: review
        restart: always
        ports: 
        - 7005:7005
        networks:
        - homebiz-net
        env_file:
        - ./env/.env

    notification:
        image: asia.gcr.io/wad2-286702/homebiz-notification
        container_name: notification
        restart: always
        ports: 
        - 7007:7007
        networks:
        - homebiz-net
        env_file:
        - ./env/.env

    #######################################
    # Frontend Services
    #######################################
    ui: # service name
        image: asia.gcr.io/wad2-286702/homebiz-ui
        container_name: ui
        restart: always
        ports:
        - 3000:3000
        networks:
        - homebiz-net
        command: "npm run start"

    # reverse proxy
    nginx:
        image: linuxserver/swag
        container_name: nginx
        ports:
        - 80:80
        - 443:443
        volumes:
        - ./config/letsencrypt:/config
        environment:
        - EMAIL=emmanuelr.2018@smu.edu.sg
        - URL=casafair.org
        - SUBDOMAINS=www
        - VALIDATION=http
        - TZ=Asia/Singapore
        - PUID=1000
        - PGID=1000
        networks:
        - homebiz-net
        depends_on:
        - ui