version: '3.7'

networks:
    homebiz-net:
        driver: bridge

services:

    #######################################
    # Backend Services
    #######################################

    user:
        build: ./user
        image: asia.gcr.io/wad2-286702/homebiz-user
        container_name: user
        restart: always
        ports: 
        - 7001:7001
        networks:
        - homebiz-net

    shop:
        build: ./shop
        image: asia.gcr.io/wad2-286702/homebiz-shop
        container_name: shop
        restart: always
        ports: 
        - 7002:7002
        networks:
        - homebiz-net

    order:
        build: ./order
        image: asia.gcr.io/wad2-286702/homebiz-order
        container_name: order
        restart: always
        ports: 
        - 7003:7003
        networks:
        - homebiz-net

    product:
        build: ./product
        image: asia.gcr.io/wad2-286702/homebiz-product
        container_name: product
        restart: always
        ports: 
        - 7004:7004
        networks:
        - homebiz-net

    review:
        build: ./review
        image: asia.gcr.io/wad2-286702/homebiz-review
        container_name: review
        restart: always
        ports: 
        - 7005:7005
        networks:
        - homebiz-net

    payment:
        build: ./payment
        image: asia.gcr.io/wad2-286702/homebiz-payment
        container_name: payment
        restart: always
        ports: 
        - 7006:7006
        networks:
        - homebiz-net

    search:
        build: ./search
        image: asia.gcr.io/wad2-286702/homebiz-search
        container_name: search
        restart: always
        ports: 
        - 7009:7009
        networks:
        - homebiz-net